from __future__ import annotations

import hashlib
import os
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

from .common import (
    BUILD_MANIFEST_SCHEMA_VERSION,
    EDPL_FORMAT_MAJOR,
    EDPL_FORMAT_MINOR,
    FINGERPRINT_CANONICALISATION_VERSION,
    TOOLCHAIN_IDENTITY,
    TOOLCHAIN_VERSION,
    ToolError,
    canonical_json_bytes,
    load_json,
    reject_unknown,
    require_array,
    require_int,
    require_keys,
    require_object,
    require_text,
    sha256_hex,
    validate_cpp_identifier,
    validate_cpp_namespace,
)
from .edpl import Pack, build_language_pack
from .fingerprint import Fingerprint, build_fingerprint
from .model import CatalogueDomain, SemanticModel, load_semantic_model



@dataclass(frozen=True)
class GeneratedSet:
    root: Path
    model: SemanticModel
    fingerprint: Fingerprint
    build_manifest: dict


@dataclass(frozen=True)
class VerifiedOutput:
    path: str
    kind: str
    sha256: str
    language: str | None = None


def _cpp_identifier(value: str | None, description: str) -> str:
    if value is None:
        raise ToolError(f"{description} symbol is required")

    return validate_cpp_identifier(
        value,
        f"{description} symbol",
    )


def _cpp_namespace_open(parts: tuple[str, ...]) -> str:
    return "\n".join(f"namespace {part} {{" for part in parts)


def _cpp_namespace_close(parts: tuple[str, ...]) -> str:
    return "\n".join(f"}} // namespace {part}" for part in reversed(parts))


def _generate_contract_header(model: SemanticModel, fingerprint: Fingerprint, cpp_namespace: str) -> bytes:
    parts = validate_cpp_namespace(cpp_namespace)
    schema = model.schema
    type_bytes = schema.type_identifier_bytes if schema is not None else 0
    field_bytes = schema.field_identifier_bytes if schema is not None else 0
    max_language = max(len(language.encode("ascii")) for language in model.manifest.supported_languages)
    fp_values = ", ".join(f"0x{value:02X}U" for value in fingerprint.runtime)
    text = f'''#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

{_cpp_namespace_open(parts)}

/// Structural Localisation ContractFamily facts generated by EDP-Localisation {TOOLCHAIN_VERSION}.
struct GeneratedLocalisationContract final {{

    static constexpr std::uint8_t FormatMajor = {EDPL_FORMAT_MAJOR}U;
    static constexpr std::uint8_t FormatMinor = {EDPL_FORMAT_MINOR}U;

    static constexpr std::size_t SupportedLanguageCount = {len(model.manifest.supported_languages)}U;
    static constexpr std::size_t MaximumSupportedLanguageIdentifierBytes = {max_language}U;

    static constexpr std::uint8_t DomainIdentifierBytes = {model.manifest.domain_bytes}U;
    static constexpr std::uint8_t SubDomainIdentifierBytes = {model.manifest.subdomain_bytes}U;
    static constexpr std::uint8_t StringIdentifierBytes = {model.manifest.string_bytes}U;
    static constexpr std::uint8_t TypeIdentifierBytes = {type_bytes}U;
    static constexpr std::uint8_t FieldIdentifierBytes = {field_bytes}U;

    inline static constexpr std::array<std::uint8_t, 16U> ContractFamilyFingerprint = {{
        {fp_values}
    }};

}};

{_cpp_namespace_close(parts)}
'''
    return text.encode("utf-8")


def _metadata_identifier_name(string_id: int) -> str:
    return {0: "Name", 1: "Description", 2: "Copyright"}[string_id]


def _active_application_domains(model: SemanticModel) -> list[CatalogueDomain]:
    return [
        domain
        for did, domain in sorted(model.catalogue.items())
        if did >= 1 and domain.status == "active"
    ]


def _generate_identifiers_header(model: SemanticModel, cpp_namespace: str) -> bytes:
    parts = validate_cpp_namespace(cpp_namespace)
    lines: list[str] = [
        "#pragma once",
        "",
        "#include <ESPressio_Localisation.hpp>",
        '#include "GeneratedLocalisationContract.hpp"',
        "",
        _cpp_namespace_open(parts),
        "",
        "namespace LocalisationIdentifiers {",
        "",
        "using IdentifierTypes = ESPressio::Localisation::ContractIdentifiers<GeneratedLocalisationContract>;",
        "",
    ]

    for domain in _active_application_domains(model):
        domain_symbol = _cpp_identifier(domain.symbol, f"Domain {domain.identifier}")

        if domain_symbol == "IdentifierTypes":
            raise ToolError(
                f"Domain {domain.identifier} symbol 'IdentifierTypes' collides with a generated binding name"
            )

        lines.extend([
            f"namespace {domain_symbol} {{",
            "",
            f"inline constexpr IdentifierTypes::DomainIdentifier Domain{{{domain.identifier}U}};",
            "",
        ])
        for sub_id, sub in sorted(domain.subdomains.items()):
            if sub.status != "active":
                continue
            sub_symbol = _cpp_identifier(sub.symbol, f"Domain {domain.identifier}/SubDomain {sub_id}")

            if sub_symbol == "Domain":
                raise ToolError(
                    f"Domain {domain.identifier}/SubDomain {sub_id} symbol 'Domain' collides with a generated binding name"
                )

            lines.extend([
                f"namespace {sub_symbol} {{",
                "",
                f"inline constexpr IdentifierTypes::SubDomainIdentifier SubDomain{{{sub_id}U}};",
                "",
            ])
            for metadata_id in (0, 1, 2):
                name = _metadata_identifier_name(metadata_id)
                lines.extend([
                    f"inline constexpr IdentifierTypes::GeneralStringIdentifier {name}{{",
                    f"    IdentifierTypes::DomainIdentifier{{{domain.identifier}U}},",
                    f"    IdentifierTypes::SubDomainIdentifier{{{sub_id}U}},",
                    f"    IdentifierTypes::StringIdentifierValue{{{metadata_id}U}}",
                    "};",
                    "",
                ])
            for string_id, item in sorted(sub.strings.items()):
                if item.status != "active":
                    continue
                symbol = _cpp_identifier(
                    item.symbol,
                    f"Domain {domain.identifier}/SubDomain {sub_id}/String {string_id}",
                )

                if symbol in {
                    "SubDomain",
                    "Name",
                    "Description",
                    "Copyright",
                }:
                    raise ToolError(
                        f"Domain {domain.identifier}/SubDomain {sub_id}/String {string_id} "
                        f"symbol {symbol!r} collides with a generated binding name"
                    )

                lines.extend([
                    f"inline constexpr IdentifierTypes::GeneralStringIdentifier {symbol}{{",
                    f"    IdentifierTypes::DomainIdentifier{{{domain.identifier}U}},",
                    f"    IdentifierTypes::SubDomainIdentifier{{{sub_id}U}},",
                    f"    IdentifierTypes::StringIdentifierValue{{{string_id}U}}",
                    "};",
                    "",
                ])
            lines.extend([
                f"}} // namespace {sub_symbol}",
                "",
            ])
        lines.extend([
            f"}} // namespace {domain_symbol}",
            "",
        ])

    lines.extend([
        "} // namespace LocalisationIdentifiers",
        "",
        _cpp_namespace_close(parts),
        "",
    ])
    return "\n".join(lines).encode("utf-8")


def _manifest_output(path: str, kind: str, data: bytes, *, language: str | None = None) -> dict:
    item: dict[str, str] = {
        "path": path,
        "kind": kind,
        "sha256": sha256_hex(data),
    }
    if language is not None:
        item["language"] = language
    return item


def _build_outputs(model: SemanticModel, fingerprint: Fingerprint, cpp_namespace: str) -> dict[str, bytes]:
    outputs: dict[str, bytes] = {
        "GeneratedLocalisationContract.hpp": _generate_contract_header(model, fingerprint, cpp_namespace),
        "GeneratedLocalisationIdentifiers.hpp": _generate_identifiers_header(model, cpp_namespace),
    }
    for language in sorted(model.manifest.supported_languages):
        outputs[f"packs/{language}.edploc"] = build_language_pack(model, language, fingerprint)
    return outputs


def _build_manifest(model: SemanticModel, fingerprint: Fingerprint, outputs: dict[str, bytes]) -> dict:
    entries: list[dict] = []
    for path in sorted(outputs):
        language: str | None = None
        kind = "generated"
        if path == "GeneratedLocalisationContract.hpp":
            kind = "cpp-contract"
        elif path == "GeneratedLocalisationIdentifiers.hpp":
            kind = "cpp-identifiers"
        elif path.startswith("packs/") and path.endswith(".edploc"):
            kind = "language-pack"
            language = path[len("packs/"):-len(".edploc")]
        entries.append(_manifest_output(path, kind, outputs[path], language=language))
    return {
        "schemaVersion": BUILD_MANIFEST_SCHEMA_VERSION,
        "toolchain": {
            "identity": TOOLCHAIN_IDENTITY,
            "version": TOOLCHAIN_VERSION,
        },
        "edplocFormat": {
            "major": EDPL_FORMAT_MAJOR,
            "minor": EDPL_FORMAT_MINOR,
        },
        "fingerprintCanonicalisationVersion": FINGERPRINT_CANONICALISATION_VERSION,
        "contractFamilyFingerprint": fingerprint.runtime_hex,
        "contractFamilyDigestSha256": fingerprint.digest_hex,
        "terminalLanguage": model.manifest.terminal_language,
        "supportedLanguages": sorted(model.manifest.supported_languages),
        "outputs": entries,
    }


def generate_to_directory(
    source_root: Path,
    platform_bundle: Path,
    schema_inventories: Iterable[Path],
    output_root: Path,
    cpp_namespace: str,
) -> GeneratedSet:
    model = load_semantic_model(source_root, platform_bundle, schema_inventories)
    fingerprint = build_fingerprint(model)
    outputs = _build_outputs(model, fingerprint, cpp_namespace)
    build_manifest = _build_manifest(model, fingerprint, outputs)

    output_root.mkdir(parents=True, exist_ok=False)
    for relative, data in sorted(outputs.items()):
        path = output_root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    (output_root / "localisation-build-manifest.json").write_bytes(canonical_json_bytes(build_manifest))

    for language in sorted(model.manifest.supported_languages):
        pack = Pack.from_path(output_root / "packs" / f"{language}.edploc")
        if pack.language != language:
            raise ToolError(f"generated pack {language}: embedded language identity mismatch")
        if pack.fingerprint != fingerprint.runtime:
            raise ToolError(f"generated pack {language}: ContractFamilyFingerprint mismatch")
        if pack.domain_bytes != model.manifest.domain_bytes or pack.subdomain_bytes != model.manifest.subdomain_bytes or pack.string_bytes != model.manifest.string_bytes:
            raise ToolError(f"generated pack {language}: identifier-width mismatch")
    return GeneratedSet(output_root, model, fingerprint, build_manifest)


def _remove_path(path: Path) -> None:
    if not path.exists() and not path.is_symlink():
        return
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink()


def compile_generated_set(
    source_root: Path,
    platform_bundle: Path,
    schema_inventories: Iterable[Path],
    output_root: Path,
    cpp_namespace: str,
) -> GeneratedSet:
    """Validate and publish one complete generated set with rollback on publication failure."""
    source_root = source_root.resolve()
    platform_bundle = platform_bundle.resolve()
    output_root = output_root.resolve()
    schema_inputs = tuple(Path(value).resolve() for value in schema_inventories)
    output_root.parent.mkdir(parents=True, exist_ok=True)

    stage = Path(
        tempfile.mkdtemp(
            prefix=f".{output_root.name}.stage-",
            dir=output_root.parent,
        )
    )
    generated_stage = stage / "generated"

    backup = Path(
        tempfile.mkdtemp(
            prefix=f".{output_root.name}.backup-",
            dir=output_root.parent,
        )
    )
    backup.rmdir()

    published = False
    had_existing = output_root.exists()

    try:
        result = generate_to_directory(
            source_root,
            platform_bundle,
            schema_inputs,
            generated_stage,
            cpp_namespace,
        )

        if had_existing:
            os.replace(output_root, backup)

        try:
            os.replace(generated_stage, output_root)
            published = True
        except BaseException as publish_error:
            if (
                had_existing
                and backup.exists()
                and not output_root.exists()
            ):
                try:
                    os.replace(backup, output_root)
                except BaseException as restore_error:
                    raise ToolError(
                        "generated-set publication failed and automatic rollback also failed; "
                        f"the previous coherent output remains preserved at {backup}: {restore_error}"
                    ) from publish_error
            raise

        if backup.exists():
            _remove_path(backup)

        return GeneratedSet(
            output_root,
            result.model,
            result.fingerprint,
            result.build_manifest,
        )
    finally:
        if not published and generated_stage.exists():
            _remove_path(generated_stage)

        if stage.exists():
            _remove_path(stage)

        if published and backup.exists():
            _remove_path(backup)
