[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.312-1/platform-espressif32.zip
platform_packages =
    tool-esptoolpy @ https://github.com/pioarduino/esptool/releases/download/v5.4.0/esptool.zip

board = esp32dev
framework = arduino
board_build.filesystem = littlefs
monitor_speed = 115200

build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
    -std=gnu++20

build_flags =
    -std=gnu++20

lib_deps =
    EDP-Localisation=https://github.com/ESPressio-Development-Platform/EDP-Localisation.git#main
    EDP-System=https://github.com/ESPressio-Development-Platform/EDP-System.git#feature/primitives_introduction
    EDP-Platform=https://github.com/ESPressio-Development-Platform/EDP-Platform.git#main
    EDP-Platform-Portable=https://github.com/ESPressio-Development-Platform/EDP-Platform-Portable.git#main
    EDP-Memory=https://github.com/ESPressio-Development-Platform/EDP-Memory.git#main
    EDP-Persistence=https://github.com/ESPressio-Development-Platform/EDP-Persistence.git#main
    EDP-Persistence-Arduino=https://github.com/ESPressio-Development-Platform/EDP-Persistence-Arduino.git#main
